config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  post 'add_string', controller: :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	unless $redis
  	  $redis = Redis.new
  	end
  end

  def add_string
  	$redis.lpush('data', params[:text])
  	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sobesedovanie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div style="max-width: 968px; margin: 0 auto;">
  <h1>Pages#index</h1>
  <p>Find me in app/views/pages/index.html.erb</p>

  <form action="<%= add_string_path %>"  method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"

      <p>textarea</p>
    <textarea name="text" rows="6" cols="20"></textarea>

    <input type="submit" value="Submit">
  </form>

  <% $redis.lrange('data', 0, -1).each do |string| %>
    <div>
      <p><%= string %></p>
    </div>
  <% end %>
</div>